<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/09/15 13:06:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=qdpm;host=localhost',
  'profiler' => false,
  'username' => 'root',
  'password' => 'Indigo%232017',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
